[package]
name = "rsemu-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rsemu_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

rsemu-core.workspace = true
rsemu-peripherals.workspace = true
rsemu-targets.workspace = true
